### ISSUE TITLE
A separate preview plugin

### ISSUE THREAD

**Issue by richardgazdik** [matt-curtis/Fluid-for-Sketch#110]
Sketch now more or less supports everything that this plugin has been created for. Although one thing is greatly missing: a standalone plugin that supports a quick preview of mobile designs on different screen sizes.

**Comment by matt-curtis** [comment]
I'm assuming you're referring to Sketch's auto-sizing, right? Auto-sizing applies to the layers inside a group, so in order for those layers to change size or position, their parent group has to change size.

So, if I'm understanding you, a separate plugin wouldn't help because groups on their own have no constraints...
