### ISSUE TITLE
Installs via Sketch Toolbox do not work

### ISSUE THREAD

**Issue by einancunlu** [matt-curtis/Fluid-for-Sketch#15]
I guess having a same name with other plugin wasn't the problem, still it doesn't work when I install the plugin with Sketch Toolbox. It gives these errors on console when I try to toggle toolbox:

![screen shot 2015-11-04 at 12 00 25 pm](https://cloud.githubusercontent.com/assets/1511689/10933765/7d74599e-82e3-11e5-949c-7de5d27988cf.png)

I tried to restart the Sketch but didn't work. It works when I install it by downloading it from here and double clicking.

**Comment by matt-curtis** [comment]
## **Solution:** install manually, see README.

This is a weird one.

It seems to be a result of the framework failing to load, which seems to be caused by Sketch Toolbox failing to download the framework properly, and therefore mangling the aliases within...

I'm going to see what changes I can make to the binaries to get this working, but in the meantime, I've opened an issue over on the [Sketch Toolbox repo](https://github.com/buzzfeed/Sketch-Toolbox/issues/61)
