### ISSUE TITLE
Fluid's definition of "Previous sibling (layer)" seems backwards

### ISSUE THREAD

**Issue by lukeadamson** [matt-curtis/Fluid-for-Sketch#26]
When you have a set of layers that looks like this in Sketch's layer panel:
- Group 1
  - Layer B
  - Layer A

Fluid seems to think that "Layer B" is the previous sibling of "Layer A", but that's backwards. Sketch renders from bottom up, so first comes Layer A, then comes Layer B, which means that Layer A is the previous sibling of Layer B. It looks a little counterintuitive, but that's the real rendering order.

This matters quite a bit when the layers overlap. You can't simply change the order of layers in the layer tree to match Fluid's definition without affecting how they actually render (and probably occluding layers you wanted to be able to see).

**Comment by rorysmyth** [comment]
+1

**Comment by matt-curtis** [comment]
You're right, somehow I missed this, we'll correct it ASAP.

**Comment by pulpy** [comment]
So if this is the case, would it be possible to then have a Following Sibling constraint added? Because if you have a layer (say a header layer that has a transparent drop shadow. If following above diagram it would be layer B) to be in the Z axis space above, say a list of info rows and you want to constrain the list group ( I put them in a group so I will call it List group. Layer A in above diagram) to the Header layer Group but below it in Z axis so the header layer will appear top have a drop shadow on the list group? Make sense? 

I love this plug in btw keep up the good work!, Can't stop using it on pretty much every layer. Do I need to do this, probably not, but I feel that repeated elements would stay more consistent though out the apps I design if I tweak sizes of elements here and there.

**Comment by matt-curtis** [comment]
@pulpy 

So as I understand it, you've got:
- Parent Group or Artboard
  - Layer B (Header)
  - Layer A (List Group)

And you want to constrain List Group to Header, right? I can see how a Next/Following Sibling option would be useful. At the time, though, the way Fluid resolves relativity and constraints doesn't make this possible...

However, I'll definitely consider it. Create a separate issue for it :)
